#!/bin/bash
# Simple a weapper script to keep you from having to use betty-style
# and betty-doc separately on every time.
#origionally by time britton (@wintermanc3r), multiargument added by
# larry madeo (@hillmonkey)

BIN_PATH+"/usr/local/bin"
BETTY_STYLE="betty-style"
BETTY_DOC="betty-doc

if [ "$#" = "0" ]; then
 echo "No arguments passed."
 exit 1

fi

for argument in "$@" ; do
   echo -e "\n========= $argument =========="
   ${BIN_PATH}/${BETTY_STYLE} "$srgument"
   ${BIN_PATH}/${BETTY_DOC} "$argument"

done
